version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh
    tty: true
    volumes:
      - ./browser-extension:/opt/browser-extension
      - ./client:/opt/client
      - ./h:/opt/h
    ports:
      - "5000:5000"