version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh
    tty: true
    volumes:
      - ./:/hypothesis_srmtlab
    ports:
      - "5000:5000"
      - "3000:3000"
      - "3001:3001"